#define a versão do docker-compose
version: '3.8'
 
services:
  # serviço do banco de dados
  db:
    #imagem do postgres
    image: postgres:13-alpine
    container_name: tp1_db

    #variaveis para configuração do banco
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce

    #volume para persistência dos dados
    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    networks: #network para comunicação entre os containers
      - app-network

    #healthcheck para verificar se o banco está pronto para aceitar conexões
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

  # SERVIÇO DA APLICAÇÃO PYTHON
  app:
    build: .
    container_name: tp1_python_app

    #app só inicia após o banco estar saudável
    depends_on:
      db:
        condition: service_healthy

    environment:
      DB_HOST: db
      #mesmas variáveis de db
      DB_NAME: ecommerce
      DB_USER: postgres
      DB_PASSWORD: postgres

    volumes:
      - ./data:/data:ro #permissão de leitura do data do diretorio host para o container atraves de um "atalho"
    
    #comando para rodar o script python
    command: python src/tp1_3.2.py

    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: